----------------------------------------------
 NDOM (max-20, no of rectangular regions created using x1,X2,Z2(as fraction of total), Vdom is the potential in that region)
  4
----------------------------------------------
 x1     z1      x2      z2       VDOM  
  0.     0.      0.      1.       0.    
  1.     0.      1.      1.       0.
  0.     1.      1.      1.       0.
  0.     0.      1.      0.       0.  
 ----------------------------------------------

